name: nareia_technical_assessment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.3
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  localization: ^2.1.0
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
